# Material Deep Ocean
# Adapted from https://github.com/marko-cerovac/material.nvim

set -ogq @thm_bg "#0F111A"
set -ogq @thm_fg "#A6ACCD"
set -ogq @thm_bg1 "#1A1C25"
set -ogq @thm_black "#464B5D"
set -ogq @thm_red "#F07178"
set -ogq @thm_green "#C3E88D"
set -ogq @thm_yellow "#FFCB6B"
set -ogq @thm_orange "#F78C6C"
set -ogq @thm_blue "#82AAFF"
set -ogq @thm_magenta "#C792EA"
set -ogq @thm_cyan "#89DDFF"
set -ogq @thm_white "#EEFFFF"
set -ogq @thm_dark "#717CB4"
set -ogq @thm_border "#232637"

set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

set-option -g status-style "bg=#{@thm_bg1},fg=#{@thm_fg},default"
set-window-option -g window-status-style "fg=#{@thm_fg},bg=#{@thm_bg},dim"
set-window-option -g window-status-current-style "fg=#{@thm_orange},bg=default,bright"

set -g pane-border-lines heavy
set -g pane-border-style "fg=#{@thm_border},dim"
set -g pane-active-border-style "fg=#{@thm_green},bold"

set-option -g display-panes-active-colour "#C3E88D"
set-option -g display-panes-colour "#A6ACCD"
set-window-option -g clock-mode-colour "#C3E88D"

set -g mode-style "fg=#{@thm_blue},bg=#{@thm_bg}"
set -g message-style "fg=#{@thm_blue},bg=#{@thm_bg1}"
set -g message-command-style "fg=#{@thm_blue},bg=#{@thm_bg}"

set -g status "on"
set -g status-interval 1
set -g status-position 'top'
set -g status-justify "left"
set -g status-bg "#1A1C25"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#{@thm_bg1},bg=#{@thm_cyan},bold]  #(whoami)(#S) \[#I:#P\] #[fg=#{@thm_cyan},bg=#{@thm_bg1},bold]"
set -g status-right "#[fg=#{@thm_bg},bg=#{@thm_dark}]  #h "

setw -g window-status-activity-style "underscore,fg=#{@thm_green},bg=#{@thm_bg1}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#{@thm_black},bg=#{@thm_bg1}"
setw -g window-status-format '#[fg=#{@thm_black},bg=#{@thm_bg1}] #[fg=#{@thm_black},bg=#{@thm_bg1},bold] #I:#W '
setw -g window-status-current-format '#[fg=#{@thm_green},bg=#{@thm_bg1}] #[fg=#{@thm_green},bg=#{@thm_bg1},bold] #I:#W '

set -g popup-border-lines rounded
set -g popup-border-style "fg=#{@thm_green}"
set -g copy-mode-selection-style "fg=#{@thm_bg1},bg=#{@thm_green}"
set -g copy-mode-match-style "fg=#{@thm_bg1},bg=#{@thm_blue}"
set -g copy-mode-current-match-style "fg=#{@thm_bg1},bg=#{@thm_orange}"
