# Material Deep Ocean
# Adapted from https://github.com/marko-cerovac/material.nvim

theme[main_bg]="#0F111A"
theme[main_fg]="#A6ACCD"
theme[title]="#EEFFFF"
theme[hi_fg]="#89DDFF"
theme[selected_bg]="#1F2233"
theme[selected_fg]="#84FFFF"
theme[inactive_fg]="#464B5D"
theme[graph_text]="#717CB4"
theme[proc_misc]="#C792EA"

theme[cpu_box]="#82AAFF"
theme[mem_box]="#C3E88D"
theme[net_box]="#89DDFF"
theme[proc_box]="#C792EA"
theme[div_line]="#232637"

theme[temp_start]="#82AAFF"
theme[temp_mid]="#FFCB6B"
theme[temp_end]="#F07178"

theme[cpu_start]="#89DDFF"
theme[cpu_mid]="#82AAFF"
theme[cpu_end]="#C792EA"

theme[free_start]="#F07178"
theme[free_mid]="#FFCB6B"
theme[free_end]="#C3E88D"

theme[cached_start]="#82AAFF"
theme[cached_mid]="#89DDFF"
theme[cached_end]="#C3E88D"

theme[available_start]="#F07178"
theme[available_mid]="#FFCB6B"
theme[available_end]="#C3E88D"

theme[used_start]="#C3E88D"
theme[used_mid]="#FFCB6B"
theme[used_end]="#F07178"

theme[download_start]="#C3E88D"
theme[download_mid]="#89DDFF"
theme[download_end]="#82AAFF"

theme[upload_start]="#FFCB6B"
theme[upload_mid]="#F78C6C"
theme[upload_end]="#F07178"

theme[process_start]="#C3E88D"
theme[process_mid]="#FFCB6B"
theme[process_end]="#F07178"
