background            #1d2021
foreground            #d4be98

# black
color0  #1d2021
color8  #6a6e95

# red
color1  #ff6e5e
color9  #d11500

# green
color2  #4fe88f
color10 #008b0c

# yellow
color3  #f1ff5e
color11 #997b00

# blue
color4  #5ea1ff
color12 #0057d1

# magenta
color5  #86a7df
color13 #d100bf

#cyan
color6  #7cf8f7
color14 #008c99

#white
color7  #FF79C6
color15 #f40064

active_tab_foreground   #1d2021
active_tab_background   #4fe88f
active_tab_font_style   normal
inactive_tab_foreground #1d2021
inactive_tab_background #d4be98
inactive_tab_font_style normal
tab_bar_margin_color  #1d2021
tab_bar_background #000


