background            #0B0C16
foreground            #ddf7ff

# black
color0  #0B0C16
color8  #6a6e95

# red
color1  #ff6e5e
color9  #d11500

# green
color2  #4fe88f
color10 #9cf7c2

# yellow
color3  #f1ff5e
color11 #997b00

# blue
color4  #5ea1ff
color12 #0057d1

# magenta
color5  #86a7df
color13 #cddbf4

#cyan
color6  #7cf8f7
color14 #d1fffe

#white
color7  #85E1FB
color15 #ddf7ff

active_tab_foreground   #0B0C16
active_tab_background   #4fe88f
active_tab_font_style   normal
inactive_tab_foreground #0B0C16
inactive_tab_background #ddf7ff
inactive_tab_font_style normal
tab_bar_margin_color  #0B0C16
tab_bar_background #000


