## name: Material Deep Ocean
## author: Adapted from marko-cerovac/material.nvim
## upstream: https://github.com/marko-cerovac/material.nvim

background #090B10
foreground #A6ACCD
macos_titlebar_color #090B10

selection_background #1F2233
selection_foreground #EEFFFF

cursor #FFCC00
cursor_text_color #0F111A

url_color #80CBC4

# Normal colors (material.nvim terminal_color_0 through terminal_color_7)
color0 #000000
color1 #DC6068
color2 #ABCF76
color3 #E6B455
color4 #6E98EB
color5 #B480D6
color6 #71C6E7
color7 #EEFFFF

# Bright colors (material.nvim terminal_color_8 through terminal_color_15)
color8  #464B5D
color9  #F07178
color10 #C3E88D
color11 #FFCB6B
color12 #82AAFF
color13 #C792EA
color14 #89DDFF
color15 #EEFFFF

tab_bar_background #0F111A
active_tab_foreground #84FFFF
active_tab_background #0F111A
inactive_tab_foreground #717CB4
inactive_tab_background #0F111A
active_border_color #84FFFF
inactive_border_color #232637
tab_bar_margin_color #0F111A
