"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# [ ┌─](bold #a9b665)\
# $os\
# $directory\
# $git_branch\
# $git_status\
# $git_commit\
# $fill\
# $package\
# $c\
# $cpp\
# $rust\
# ${custom.cargo_version}\
# $golang\
# $nodejs\
# $python\
# $conda\
# $docker_context\
# $time\n\
# [ └─](bold #a9b665)\
# $character\
# """

format = """
[░▒▓](#7daea3)\
$os\
$username\
[▓▒░](#7daea3)\
$directory\
$git_branch\
$git_status\
$git_commit\
$fill\
$package\
$c\
$cpp\
$rust\
${custom.cargo_version}\
$golang\
$nodejs\
$python\
$conda\
$docker_context\
$line_break\
$character\
"""

right_format = """
$cmd_duration\
"""

# add_newline = true
# continuation_prompt = '▶▶ '


[os]
disabled = false
style = "bold bg:#7daea3 fg:#1d2021"
format = '[ $symbol ]($style)'
# format = '[$symbol ]($style)'

[username]
disabled = false
style_user = "bold bg:#7daea3 fg:#1d2021"
format = '[$user ]($style)'
show_always = true

[directory]
# read_only = "[󰌾]"
# home_symbol = ""
# truncation_length = 3
# truncation_symbol = ""
style = "bold fg:#a9b665"
format = "[  $path]($style) "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[bun]
symbol = " "

[line_break]
disabled = false

[c]
symbol = " "
style = "bold fg:#ea6962"
format = '[$symbol($version(-$name) )]($style)'

[cpp]
symbol = " "
style = "bold fg:#ea6962"
format = '[$symbol($version(-$name) )]($style)'

[custom.up_left]
style = "bold fg:#a9b665"
when = true
format = '[ ┌─]($style)'

[custom.down_left]
style = "bold fg:#a9b665"
when = true
format = '[ └─]($style)'

[custom.up_right]
style = "bold fg:#a9b665"
when = true
format = '[ ─┐]($style)'

[custom.down_right]
style = "bold fg:#a9b665"
when = true
format = '[ ─┘]($style)'


[fill]
symbol = ' '
style = 'bold #a9b665'


[cmake]
symbol = " "
format = '[$symbol($version )]($style)'

[conda]
symbol = " "
format = '[$symbol$environment]($style) '


[deno]
symbol = " "



[docker_context]
symbol = " "
style = "bold fg:#e78a4e"
format = '[$symbol$context]($style) '


[custom.zvm]
symbol = " "
command = "echo $ZVM_MODE"
style = "bold fg:#d3869b"
format = '[$symbol ($output)]($style) '

[git_branch]
symbol = " "
style = "bold fg:#d3869b"
format = '[$symbol$branch(:$remote_branch)]($style) '
# format = '[ $symbol $branch]($style)'

[git_status]
style = "bold fg:#d3869b"
format = '[\[($all_status$ahead_behind)\]]($style)'

[git_commit]
style = "bold fg:#d3869b"
tag_symbol = '  '

[golang]
symbol = " "
style = "bold fg:#89b482"
format = '[$symbol($version )]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "


[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "bold fg:#a9b665"
format = '[$symbol($version )]($style)'


[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳 "
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[package]
symbol = "󰏗 "
style = "bold fg:#e78a4e"
format = '[$symbol$version]($style) '


[python]
symbol = " "
style = 'bold fg:#a9b665'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style = "bold fg:#d8a657"
format = '[$symbol($version )]($style)'


[character]
disabled = false
format = '$symbol '
success_symbol = '[❯](bold #7daea3)'
error_symbol = '[❮](bold #ea6962)'
vimcmd_symbol = '[❮](bold #7daea3)'
vimcmd_replace_one_symbol = '[](bold #a9b665)'
vimcmd_replace_symbol = '[](bold #a9b665)'
vimcmd_visual_symbol = '[󰜷](bold #e78a4e)'


[time]
disabled = false
style = "bold fg:#7daea3"
format = '[ $time]($style)'
time_format = "%H:%M"

[cmd_duration]
show_milliseconds = true
format = "[󰗕 in $duration ]($style)"
style = "fg:#d4be98"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[custom.cargo_version]
command = 'cat Cargo.toml|grep version|head -1|cut -f2 -d\"'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']
style = "bold fg:#e78a4e"

[custom.emoji]
description = "Displays a (pseudo) random emoji for each prompt"
# change the content of the EMOJIS array to your liking and replace the
# number 12 with the number of items in the array, minus one
command = "EMOJIS=(⛵️ 🛰 🪐 🚀 🧡 🔭 🌍 💫 ☄️ ✨ 🌠 🌌 ⭐️); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# if you are on windows, replace "true" with "1"
when = "true"
shell = ["bash", "--noprofile", "--norc"]
format = " $output"
