# Background and foreground colors
background = #1d2021
foreground = #d4be98

# Standard colors
palette = 0=#1d2021
palette = 1=#ff6e5e
palette = 2=#4fe88f
palette = 3=#f1ff5e
palette = 4=#5ea1ff
palette = 5=#86a7df
palette = 6=#7cf8f7
palette = 7=#FF79C6

# Bright colors
palette = 8=#6a6e95
palette = 9=#d11500
palette = 10=#008b0c
palette = 11=#997b00
palette = 12=#0057d1
palette = 13=#d100bf
palette = 14=#008c99
palette = 15=#f40064
