gui:
  theme: # catppuccin palette of course
    activeBorderColor:
      # Previous palette: - "#ea6962"
      - "#F07178"
    inactiveBorderColor:
      # Previous palette: - "#665c54"
      - "#464B5D"
    searchingActiveBorderColor:
      # Previous palette: - "#a9b665"
      - "#C3E88D"
    selectedLineBgColor:
      # Previous palette: - "#928374"
      - "#717CB4"
    cherryPickedCommitBgColor:
      # Previous palette: - "#d3869b"
      - "#C792EA"
    cherryPickedCommitFgColor:
      # Previous palette: - "#7daea3"
      - "#82AAFF"
    unstagedChangesColor:
      # Previous palette: - "#e78a4e"
      - "#F78C6C"
    defaultFgColor:
      # Previous palette: - "#d4be98"
      - "#A6ACCD"
    optionsTextColor:
      # Previous palette: - "#7daea3"
      - "#82AAFF"

  authorColors:
    # Previous palette: "*": "#d8a657"
    "*": "#FFCB6B"
  showBottomLine: true
  border: rounded
  nerdFontsVersion: "3"
  spiner:
    frames:
      - ⣾
      - ⣽
      - ⣻
      - ⢿
      - ⡿
      - ⣟
      - ⣯
      - ⣷
os:
  edit: "nvim"
# promptToReturnFromSubprocess:
#   false
# universal:
#   quit: Q
