gui:
  theme: # catppuccin palette of course
    activeBorderColor:
      - "#ea6962"
    inactiveBorderColor:
      - "#665c54"
    searchingActiveBorderColor:
      - "#a9b665"
    selectedLineBgColor:
      - "#928374"
    cherryPickedCommitBgColor:
      - "#d3869b"
    cherryPickedCommitFgColor:
      - "#7daea3"
    unstagedChangesColor:
      - "#e78a4e"
    defaultFgColor:
      - "#d4be98"
    optionsTextColor:
      - "#7daea3"

  authorColors:
    "*": "#d8a657"
  showBottomLine: true
  border: rounded
  nerdFontsVersion: "3"
  spiner:
    frames:
      - ⣾
      - ⣽
      - ⣻
      - ⢿
      - ⡿
      - ⣟
      - ⣯
      - ⣷
os:
  edit: "nvim"
# promptToReturnFromSubprocess:
#   false
# universal:
#   quit: Q
