gui:
  theme: # catppuccin palette of course
    activeBorderColor:
      - "#ff5ea0"
    inactiveBorderColor:
      - "#3c5868"
    searchingActiveBorderColor:
      - "#4fe88f"
    selectedLineBgColor:
      - "#3c5868"
    cherryPickedCommitBgColor:
      - "#1e2124"
    cherryPickedCommitFgColor:
      - "#aca1cf"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ddf7ff"
    optionsTextColor:
      - "#5ea1ff"

  authorColors:
    "*": "#ff79c6"
  showBottomLine: true
  border: rounded
  nerdFontsVersion: "3"
  spiner:
    frames:
      - ⣾
      - ⣽
      - ⣻
      - ⢿
      - ⡿
      - ⣟
      - ⣯
      - ⣷
os:
  edit: "nvim"
# promptToReturnFromSubprocess:
#   false
# universal:
#   quit: Q
