require("config.options")
require("config.keymaps")
require("config.autocmds")

--plugins
require("plugins.theme")
require("plugins.whichkey")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.ui")
require("plugins.oil")
require("plugins.git")
require("plugins.mini")
require("plugins.conform")
require("plugins.blink")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.marks")
require("plugins.multicursor")
require("plugins.flash")
require("plugins.yanky")
require("plugins.tools")

require("plugins.python")
require("plugins.markdown")
-- lsp
require("plugins.lsp")
