onboarding = false
[terminal]
shell_mode = "auto"

[keys]
prefix = "ctrl+b"
detach = "prefix+d"
goto = "prefix+g"
next_tab = "prefix+tab"
previous_tab = "prefix+shift+tab"
close_workspace = "prefix+shift+d"
navigate_workspace_up = "up"
navigate_workspace_down = "down"
navigate_pane_left = "h"
navigate_pane_down = "j"
navigate_pane_up = "k"
navigate_pane_right = "l"
remote_image_paste = "ctrl+v"
new_tab = "prefix+c"
switch_tab = "prefix+1..9"
rename_tab = "prefix+r"
close_tab = "prefix+shift+x"
copy_mode = "prefix+v"

focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
swap_pane_left = "prefix+shift+h"
swap_pane_down = "prefix+shift+j"
swap_pane_up = "prefix+shift+k"
swap_pane_right = "prefix+shift+l"
last_pane = ""
split_vertical = "prefix+backslash"
split_horizontal = "prefix+minus"
close_pane = "prefix+x"
zoom = "prefix+z"
resize_mode = "prefix+shift+r"
toggle_sidebar = "prefix+b"

remove_worktree = "prefix+alt+d"
reload_config = "prefix+ctrl+r"

# workspace
workspace_picker = "prefix+w"
rename_workspace = "prefix+shift+w"
new_workspace = "prefix+shift+n"
previous_workspace = "prefix+p"
next_workspace = "prefix+n"
open_worktree = "prefix+shift+o"
new_worktree = "prefix+shift+g"
switch_workspace = "prefix+ctrl+1..9"

focus_agent = "prefix+alt+1..9"



[theme]
name = "terminal"
auto_switch = false

[ui.toast]
delivery = "off"
delay_seconds = 1

[ui.toast.herdr]
position = "bottom-right"

[ui.toast.clipboard]
enabled = true
position = "bottom-center"

