set -ogq @thm_bg "#1d2021"
set -ogq @thm_fg "#d4be98"
set -ogq @thm_bg1 "#0B0C12"

# Colors
set -ogq @thm_black "#665c54"
set -ogq @thm_red "#ea6962"
set -ogq @thm_green "#a9b665"
set -ogq @thm_yellow "#e78a4e"
set -ogq @thm_blue "#7daea3"
set -ogq @thm_magenta "#d3869b"
set -ogq @thm_cyan "#89b482"
set -ogq @thm_white "#d4be98"




set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

# default statusbar colors
set-option -g status-style bg=#1d2021,fg=#d4be98,default

# default window title colors
set-window-option -g window-status-style fg=#d4be98,bg=#1d2021,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default,bright

# pane border
set-option -g pane-border-style fg=#a9b665 #base02
set-option -g pane-active-border-style fg=#a9b665,bg=#1d2021

# message text
set-option -g message-style bg=#1d2021,fg=#a9b665

# pane number display
set-option -g display-panes-active-colour "#a9b665"
set-option -g display-panes-colour "#d4be98"

# clock
set-window-option -g clock-mode-colour "#a9b665"

# status line
set -g mode-style "fg=#{@thm_blue},bg=#{@thm_bg}"

set -g message-style "fg=#{@thm_blue},bg=#{@thm_bg}"
set -g message-command-style "fg=#{@thm_blue},bg=#{@thm_bg}"

set -g pane-border-style "fg=#{@thm_fg}"
set -g pane-active-border-style "fg=#{@thm_green}"


set -g status "on"
set -g status-interval 1
set -g status-position 'top'
set -g status-justify "left"

set -g status-style "fg=#d4be98,bg=#1d2021"

set -g status-bg "#0B0C12"


set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#{@thm_blue},bg=#{@thm_bg1},bold]  #(whoami)(#S) \[#I:#P\]  #[fg=#{@thm_fg},bg=#{@thm_bg1},bold]\ue0b0 "
set -g status-right "#[fg=#{@thm_cyan},bg=#{@thm_bg1},nobold,nounderscore,noitalics] #{pane_current_path} #[fg=#{@thm_fg},bg=#{@thm_bg1}]\ueb10#[fg=#{@thm_magenta},bg=#{@thm_bg1},bold]  #h "

setw -g window-status-activity-style "underscore,fg=#{@thm_green},bg=#{@thm_bg1}"
setw -g window-status-separator "\ueb10"
setw -g window-status-style "NONE,fg=#{@thm_black},bg=#{@thm_bg1}"
setw -g window-status-format '#[fg=#{@thm_black},bg=#{@thm_bg1}] #[fg=#{@thm_black},bg=#{@thm_bg1},bold] #I:#W '
setw -g window-status-current-format '#[fg=#{@thm_green},bg=#{@thm_bg1}] #[fg=#{@thm_green},bg=#{@thm_bg1},bold] #I:#W '

set -g popup-border-lines rounded  # 圆角边框
set -g popup-border-style fg='#a9b665'

set -g message-style "fg='#0B0C12',bg='#ea6962',bold"

# ========== 复制模式样式核心 ==========
# 选中文字高亮
set -g copy-mode-selection-style fg='#0B0C12',bg='#a9b665'

# 搜索匹配项样式（可选）
set -g copy-mode-match-style fg='#0B0C12',bg='#7daea3'
set -g copy-mode-current-match-style fg='#0B0C12',bg='#e78a4e'
